/*
 * Backend for Online Shop
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

type Cart struct {
	UserID   int64  `json:"userID,omitempty"`
	Date     string `json:"date,omitempty"`
	Products []Item `json:"products,omitempty"`
}
