/*
 * Backend for Online Shop
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

import "github.com/google/uuid"

type Item struct {
	Id          uuid.UUID `json:"id,omitempty"`
	Title       string    `json:"title,omitempty"`
	Description string    `json:"description,omitempty"`
	Price       int32     `json:"price,omitempty"`
	Category    Category `json:"category,omitempty"`
	Vendor      string    `json:"vendor,omitempty"`
	Image       string    `json:"image,omitempty"`
}
