/*
 * Backend for Online Shop
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package onlineShopBackend

import (
	"OnlineShopBackend/pkg/app"
	"go.uber.org/zap"
	"io"
	"net/http"

	"github.com/gin-gonic/gin"
)

// CreateCategory -
func CreateCategory(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// CreateItem - Create a new item
func CreateItem(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// GetItem -
func GetItem(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// UpdateItem - Update an item
func UpdateItem(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// UploadFile - upload an image
func UploadFile(c *gin.Context) {
	l := app.GlobalApp.Log.Logger
	id := c.Param("itemID")
	name := ""
	file, err := io.ReadAll(c.Request.Body)

	if err != nil {
		c.JSON(http.StatusUnsupportedMediaType, gin.H{})
	}

	l.Info("Read id", zap.String("id", id))
	l.Info("File len=", zap.Int32("len", int32(len(file))))
	err = app.GlobalApp.Fs.PutFile(id, name, file)

	if err != nil {
		c.JSON(http.StatusInsufficientStorage, gin.H{})
		return
	}

	c.JSON(http.StatusCreated, gin.H{})
}
