/*
 * Backend for Online Shop
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package onlineShopBackend

type User struct {
	Firstname string `json:"firstname,omitempty"`

	Lastname string `json:"lastname,omitempty"`

	Email string `json:"email,omitempty"`

	Address UserAddress `json:"address,omitempty"`
}
