/*
 * Backend for Online Shop
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package delivery

import (
	"io"
	"net/http"

	"go.uber.org/zap"

	"github.com/gin-gonic/gin"
)

// UploadFile - upload an image
func (delivery *Delivery) UploadFile(c *gin.Context) {
	id := c.Param("itemID")
	name := ""
	file, err := io.ReadAll(c.Request.Body)

	if err != nil {
		c.JSON(http.StatusUnsupportedMediaType, gin.H{})
	}

	delivery.logger.Info("Read id", zap.String("id", id))
	delivery.logger.Info("File len=", zap.Int32("len", int32(len(file))))
	err = delivery.filestorage.PutFile(id, name, file)

	if err != nil {
		c.JSON(http.StatusInsufficientStorage, gin.H{})
		return
	}

	c.JSON(http.StatusCreated, gin.H{})
}
