/*
 * Backend for Online Shop
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package delivery

import (
	"net/http"

	"github.com/gin-gonic/gin"
)

// GetCart - get user cart
func (delivery *Delivery) GetCart(c *gin.Context) {
	delivery.logger.Debug("Enter in delivery GetCart()")

	ctx := c.Request.Context()

	quantity, err := delivery.itemHandlers.ItemsQuantity(ctx)
	if err != nil {
		c.JSON(http.StatusInternalServerError, gin.H{"error": err.Error()})
		return
	}
	itemsQuantity := ItemsQuantity{Quantity: quantity}

	c.JSON(http.StatusOK, gin.H{})
}
