/*
 * Backend for Online Shop
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package delivery

import (
	"net/http"

	"github.com/gin-gonic/gin"
)

// GetCart - get user cart
func GetCart(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

