/*
 * Backend for Online Shop
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package delivery

import (
	"net/http"

	"github.com/gin-gonic/gin"
)



// CreateItem - Create a new item
func CreateItem(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// GetItem -
func GetItem(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// UpdateItem - Update an item
func UpdateItem(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// UploadFile - upload an image
func UploadFile(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}


// ItemsList - List of Items with filters
func ItemsList(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// SearchLine -
func SearchLine(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}
