/*
 * Backend for Online Shop
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package router

import (
	"OnlineShopBackend/internal/delivery"
	"OnlineShopBackend/internal/delivery/swagger/docs"
	"net/http"

	ginzap "github.com/gin-contrib/zap"
	"github.com/gin-gonic/gin"
	swaggerFiles "github.com/swaggo/files"
	ginSwagger "github.com/swaggo/gin-swagger"
	"go.uber.org/zap"
)

// Route is the information for every URI.
type Route struct {
	// Name is the name of this Route.
	Name string
	// Method is the string for the HTTP method. ex) GET, POST etc..
	Method string
	// Pattern is the pattern of the URI.
	Pattern string
	//
	Middleware gin.HandlerFunc
	// HandlerFunc is the handler function of this route.
	HandlerFunc gin.HandlerFunc
}

// Routes is the list of the generated Route.
type Routes []Route

type Router struct {
	*gin.Engine
	delivery *delivery.Delivery
	logger   *zap.Logger
}

// NewRouter returns a new router.
func NewRouter(delivery *delivery.Delivery, logger *zap.Logger) *Router {
	logger.Debug("Enter in NewRouter()")
	gin := gin.Default()
	gin.Use(CORSMiddleware())
	gin.Use(ginzap.RecoveryWithZap(logger, true))
	gin.Static("/files", "./static/files")
	docs.SwaggerInfo.BasePath = "/"
	gin.Group("/docs").Any("/*any", ginSwagger.WrapHandler(swaggerFiles.Handler))
	router := &Router{
		delivery: delivery,
		logger:   logger,
	}

	routes := Routes{
		{
			"Index",
			http.MethodGet,
			"/",
			noOpMiddleware,
			delivery.Index,
		},
		{
			"GetFileList",
			http.MethodGet,
			"/images/list",
			AdminAuth(),
			delivery.GetFileList,
		},
		// -------------------------CATEGORY----------------------------------------------------------------------------
		{
			"CreateCategory",
			http.MethodPost,
			"/categories/create",
			AdminAuth(),
			delivery.CreateCategory,
		},
		{
			"GetCategory",
			http.MethodGet,
			"/categories/:categoryID",
			noOpMiddleware,
			delivery.GetCategory,
		},
		{
			"GetCategoryList",
			http.MethodGet,
			"/categories/list",
			noOpMiddleware,
			delivery.GetCategoryList,
		},
		{
			"UpdateCategory",
			http.MethodPut,
			"/categories/:categoryID",
			AdminAuth(),
			delivery.UpdateCategory,
		},
		{
			"UploadCategoryImage",
			http.MethodPost,
			"/categories/image/upload/:categoryID",
			AdminAuth(),
			delivery.UploadCategoryImage,
		},
		{
			"DeleteCategoryImage",
			http.MethodDelete,
			"/categories/image/delete", //?id=25f32441-587a-452d-af8c-b3876ae29d45&name=20221209194557.jpeg
			AdminAuth(),
			delivery.DeleteCategoryImage,
		},
		{
			"DeleteCategory",
			http.MethodDelete,
			"/categories/delete/:categoryID",
			AdminAuth(),
			delivery.DeleteCategory,
		},
		// -------------------------ITEM--------------------------------------------------------------------------------
		{
			"CreateItem",
			http.MethodPost,
			"/items/create",
			AdminAuth(),
			delivery.CreateItem,
		},
		{
			"GetItem",
			http.MethodGet,
			"/items/:itemID",
			noOpMiddleware,
			delivery.GetItem,
		},
		{
			"GetItemsByCategory",
			http.MethodGet,
			"/items/", //?param=categoryName&offset=20&limit=10&sort_type=name&sort_order=asc (sort_type == name or price, sort_order == asc or desc)
			noOpMiddleware,
			delivery.GetItemsByCategory,
		},
		{
			"UpdateItem",
			http.MethodPut,
			"/items/update",
			AdminAuth(),
			delivery.UpdateItem,
		},
		{
			"UploadItemImage",
			http.MethodPost,
			"/items/image/upload/:itemID",
			AdminAuth(),
			delivery.UploadItemImage,
		},
		{
			"DeleteItemImage",
			http.MethodDelete,
			"/items/image/delete", //?id=25f32441-587a-452d-af8c-b3876ae29d45&name=20221209194557.jpeg
			AdminAuth(),
			delivery.DeleteItemImage,
		},
		{
			"ItemsQuantity",
			http.MethodGet,
			"/items/quantity",
			noOpMiddleware,
			delivery.ItemsQuantity,
		},
		{
			"ItemsQuantityInCategory",
			http.MethodGet,
			"/items/quantityCat/:categoryName",
			noOpMiddleware,
			delivery.ItemsQuantityInCategory,
		},
		{
			"ItemsQuantityInFavourite",
			http.MethodGet,
			"/items/quantityFav/:userID",
			noOpMiddleware,
			delivery.ItemsQuantityInFavourite,
		},
		{
			"ItemsQuantityInSearch",
			http.MethodGet,
			"/items/quantitySearch/:searchRequest",
			noOpMiddleware,
			delivery.ItemsQuantityInSearch,
		},
		{
			"ItemsList",
			http.MethodGet,
			"/items/list", //?offset=20&limit=10&sort_type=name&sort_order=asc (sort_type == name or price, sort_order == asc or desc)
			noOpMiddleware,
			delivery.ItemsList,
		},
		{
			"SearchLine",
			http.MethodGet,
			"/items/search/", //?param=searchRequest&offset=20&limit=10&sort_type=name&sort_order=asc (sort_type == name or price, sort_order == asc or desc)
			noOpMiddleware,
			delivery.SearchLine,
		},
		{
			"DeleteItem",
			http.MethodDelete,
			"/items/delete/:itemID",
			AdminAuth(),
			delivery.DeleteItem,
		},
		{
			"AddFavouriteItem",
			http.MethodPost,
			"/items/addFavItem",
			UserAuth(),
			delivery.AddFavouriteItem,
		},
		{
			"DeleteFavouriteItem",
			http.MethodDelete,
			"/items/deleteFav/:userID/:itemID",
			UserAuth(),
			delivery.DeleteFavouriteItem,
		},
		{
			"GetFavouriteItems",
			http.MethodGet,
			"/items/favList/", //?param=userIDt&offset=20&limit=10&sort_type=name&sort_order=asc (sort_type == name or price, sort_order == asc or desc)
			UserAuth(),
			delivery.GetFavouriteItems,
		},
		// -------------------------CART--------------------------------------------------------------------------------
		{
			"GetCart",
			http.MethodGet,
			"/cart/:cartID",
			UserAuth(),
			delivery.GetCart,
		},
		{
			"GetCartByUserId",
			http.MethodGet,
			"/cart/byUser/:userID",
			UserAuth(),
			delivery.GetCartByUserId,
		},
		{
			"CreateCart",
			http.MethodPost,
			"/cart/create/:userID",
			UserAuth(),
			delivery.CreateCart,
		},
		{
			"AddItemToCart",
			http.MethodPut,
			"/cart/addItem",
			UserAuth(),
			delivery.AddItemToCart,
		},
		{
			"DeleteItemFromCart",
			http.MethodDelete,
			"/cart/delete/:cartID/:itemID",
			UserAuth(),
			delivery.DeleteItemFromCart,
		},
		{
			"DeleteCart",
			http.MethodDelete,
			"/cart/delete/:cartID",
			UserAuth(),
			delivery.DeleteCart,
		},
		// -------------------------USER--------------------------------------------------------------------------------
		{
			"CreateUser",
			http.MethodPost,
			"/user/create",
			noOpMiddleware,
			delivery.CreateUser,
		},
		{
			"LoginUser",
			http.MethodPost,
			"/user/login",
			noOpMiddleware,
			delivery.LoginUser,
		},
		{
			"LogoutUser",
			http.MethodGet,
			"/user/logout",
			noOpMiddleware,
			delivery.LogoutUser,
		},
		{
			"LoginUserGoogle",
			http.MethodGet,
			"/user/login/google",
			noOpMiddleware,
			delivery.LoginUserGoogle,
		},
		{
			"callbackGoogle",
			http.MethodGet,
			"/user/callbackGoogle",
			noOpMiddleware,
			delivery.CallbackGoogle,
		},

		{
			"userProfile",
			http.MethodGet,
			"/user/profile",
			UserAuth(),
			delivery.UserProfile,
		},
		{
			"userProfileUpdate",
			http.MethodPut,
			"/user/profile/edit",
			UserAuth(),
			delivery.UserProfileUpdate,
		},
		{
			"tokenUpdate",
			http.MethodPost,
			"/user/token/update",
			UserAuth(),
			delivery.TokenUpdate,
		},
		{
			"ChangeRole",
			http.MethodPut,
			"/user/role/update",
			AdminAuth(),
			delivery.ChangeRole,
		},
		{
			"UserRolesList",
			http.MethodGet,
			"/user/rights/list",
			AdminAuth(),
			delivery.RolesList,
		},
		{
			"CreateRights",
			http.MethodPost,
			"/user/createRights",
			AdminAuth(),
			delivery.CreateRights,
		},
		// -------------------------ORDER--------------------------------------------------------------------------------
		{
			"CreateOrder",
			http.MethodPost,
			"/order/create",
			UserAuth(),
			delivery.CreateOrder,
		},
		{
			"GetOrder",
			http.MethodGet,
			"/order/:orderID",
			UserAuth(),
			delivery.GetOrder,
		},
		{
			"GetOrdersForUsers",
			http.MethodGet,
			"/order/list/:userID",
			UserAuth(),
			delivery.GetOrdersForUser,
		},
		{
			"DeleteOrder",
			http.MethodDelete,
			"/order/delete/:orderID",
			AdminAuth(),
			delivery.DeleteOrder,
		},
		{
			"ChangeAddress",
			http.MethodPatch,
			"/order/changeaddress",
			UserAuth(),
			delivery.ChangeAddress,
		},
		{
			"ChangeStatus",
			http.MethodPatch,
			"/order/changestatus",
			AdminAuth(),
			delivery.ChangeStatus,
		},
	}

	for _, route := range routes {
		switch route.Method {
		case http.MethodGet:
			gin.GET(route.Pattern, route.Middleware, route.HandlerFunc)
		case http.MethodPost:
			gin.POST(route.Pattern, route.Middleware, route.HandlerFunc)
		case http.MethodPut:
			gin.PUT(route.Pattern, route.Middleware, route.HandlerFunc)
		case http.MethodPatch:
			gin.PATCH(route.Pattern, route.Middleware, route.HandlerFunc)
		case http.MethodDelete:
			gin.DELETE(route.Pattern, route.Middleware, route.HandlerFunc)
		}
	}
	router.Engine = gin
	return router
}
