/*
 * Backend for Online Shop
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package main

import (
	sw "OnlineShopBackend/cmd/onlineShopBackend/api"
	"OnlineShopBackend/pkg/app"
	"log"
)

func main() {
	router := sw.NewRouter()

	go log.Fatal(router.Run(":8000"))

	a := app.NewApp(nil)
	log.Printf("Server started")
	a.Start()
}
